name: README Build

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 */1 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v1

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: '17.x'

      - name: cache
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-js-${{ hashFiles('package-lock.json') }}

      - name: install dependencies
        run: npm install

      - name: generate README file
        run: node services/main.js
        env:
          owo: uwu

      - name: push new README.md
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}